### ISSUE TITLE
Horrible error in elm-package.json

### ISSUE THREAD

**Issue by ilyagr** [vilterp/elm-diagrams#41]
Then module "Diagrams.Type" is not listed in `exposed-modules`. As a result, I can't get anything to compile.

**Comment by vilterp** [comment]
Whoops! I'll fix that. Was using it as a submodule in my other project for so long, I missed it…

**Comment by vilterp** [comment]
Finally fixed this in 7.2. Sorry it took so long. Had to make a `Diagrams.RealType` so I could expose the type without the constructors, but allow internal modules to access the constructors.
